am2_question_bank = [
    "What is Machine Learning?",
    "What is Data Science?",
    "Tell me about a time that you used machine learning (supervised or unsupervised) to solve a business problem.",
    "Describe a project where you applied supervised machine learning to meet a business objective. What was the objective, and how did the model impact the business?",
    "Explain the principles and properties behind statistical and machine learning methods, and how you have used these techniques to solve complex business problems. Can you provide examples of how you have evaluated and improved these models?",
    "Tell me about how you’ve dealt with sources of bias in your work",
    "How do you make effective use of high-performance computer architectures?",
    "When applying machine learning methodologies, how do you strike a balance between achieving high accuracy and maintaining interpretability, especially when addressing specific business objectives?",
    "Describe the linear regression model",
    "Describe a situation where business objectives evolved, and you needed to adapt or retrain existing AI/ML models. How did you approach this, and what were the results?",
    "How have you evaluated ML solutions via analysis of test data and results from research, feasibility, acceptance, and usability testing?",
    "Can you explain the relationship between mathematical principles and core techniques in AI and data science within the context of your organisation?",
    "Discuss the programming languages and techniques that you have used for data science, and how you have applied them to create commercially beneficial scientific analysis and simulation.",
    "Describe a problem that you solved using applied research and data modelling techniques to design and refine the database and storage architectures. How did you ensure the security, stability, and scalability of the data products delivered to the business?",
    "Can you describe the process of designing algorithms for accessing and analyzing large amounts of data in the context of your work?",
    "Explain the considerations you take into account when designing algorithms that involve Application Programming Interfaces (APIs) for interacting with various data sets.",
    "How do you ensure the efficiency and scalability of algorithms designed for accessing and analysing large volumes of data?",
    "Can you share an example from your experience when you challenged the norm by investigating and proposing a solution to a problem? What was the issue, and how did your proposed solution deviate from the conventional approach?",
    "How do you evaluate software solutions via analysis of test data and results from research, feasibility, acceptance, and usability testing?",
    "How does your role fit with and support organisational strategy and objectives?",
    "How do AI and data science techniques support and enhance the work of other members of the analytical team?",
    "How do you provide direction and technical guidance for the business with regard to AI and data science opportunities?",
    "How do you coordinate, negotiate with, and manage expectations of diverse stakeholders, and suppliers with conflicting priorities, interests, and timescales?",
    "How did you justify your choice of techniques to both technical and non-technical stakeholders, considering the risks and benefits involved?",
    "Can you describe a specific initiative where you actively shared AI and data science practices across your organisation? What methods or platforms did you use to disseminate this knowledge?",
    "Describe a scenario where there were conflicting opinions and views among team members. How did you make an impartial decision that considered diverse perspectives and still served the business’s best interests?",
    "Can you give an example of a time when the circumstances of a project or business situation changed unexpectedly? How did you adapt your decision-making process to these changes while maintaining impartiality?",
    "Explain how you communicate independent decisions to diverse stakeholders, especially when opinions may differ. How do you ensure that your rationale is understood and accepted?",
    "Can you describe a specific project where you worked closely with software engineers to ensure that testing processes were integrated seamlessly with AI and data science solutions? How did this collaboration contribute to meeting organisational requirements?",
    "What do you think are the most significant roles and impacts of AI, data science, and data engineering in industry and society? How can businesses harness these technologies to create value and benefit society?",
    "How would you describe the potential roles and impact of AI and data science on your own organisation? Can you provide specific examples of how these technologies could affect various aspects within your company?",
    "Considering the broader societal context, what are the potential roles and impacts of AI and data science? How might these technologies contribute to or shape societal changes, and what considerations should be taken into account?",
    "What are some recent trends in ML/AI Have these trends resulted in ethical and social concerns and if so how do these relate to your business?",
    "When selecting procedures and methods for AI and data science projects, how do you ensure that ethical considerations are taken into account? Can you discuss a specific instance where you made choices based on ethical principles?",
    "Can you provide an example of a specific problem or challenge within your organization where you applied an ML solution that led to the enhancement of working practices? How did this solution contribute to improved efficiency or effectiveness?",
    "How do you contribute to the development of other team members? Can you discuss instances where you provided guidance that resulted in positive changes in the working practices of team members?",
    "Explain how you interpreted the organisational policies, standards, and guidelines in relation to AI and data to ensure compliance and adherence to ethical, legal, and regulatory frameworks?",
    "How would you explain the potential impact of non-compliance with ML and data protection regulations on the day-to-day operations of our business? Can you provide specific examples of how this could disrupt workflows?",
    "Can you discuss the financial and legal risks associated with non-compliance to ML and data protection regulations? How might regulatory penalties or legal action impact the business financially?",
    "How do you consider the associated regulatory, legal, ethical, and governance issues when evaluating choices at each stage of the data process?",
    "How do you select and apply the most effective/appropriate AI and data science techniques to solve complex business problems?",
    "How do you maintain awareness of trends and innovations in the subject area, utilizing a range of academic literature, online sources, community interaction, conference attendance, and other methods?",
    "How do you commit to continuous professional development, maintaining your knowledge and skills in relation to AI developments that influence your work?",
    "How did you ensure that your selected AI and data science techniques aligned with organisational requirements and goals? Can you provide examples of specific organisational considerations that influenced your choice?",
    "Can you describe a complex business problem you’ve encountered where AI and data science were applicable? How did you go about defining and understanding the nuances of this problem?",
]